domain: https://luanshiyinyang.github.io

# Conversion
exclude: ["*.lnk", "*.bat", "README.md", "Gemfile*"]

netlify.configure({'site_id': luanshiyinyang.netlify.com});
# Outputting
# DO NOT use date as url AND change timezone,
# or post would missing after upload
permalink: /posts/:title
timezone: Europe/Amsterdam
